### ISSUE TITLE
Rest easy (open source chin rest) files

### ISSUE THREAD

**Issue by arnabiswas** [MonkeyGone2Heaven/SCNI_Toolbar#4]
Files may be missing. I could not find the link to the CAD files or .STL file for custom parts of the Rest Easy open source chinrest.

**Comment by Phenomenal-Cat** [comment]
Sorry Arnab, that Wiki page was acting as a placeholder while I migrate various equipment designs to the web. I've updated the [RestEasy](https://github.com/MonkeyGone2Heaven/SCNI_Toolbar/wiki/RestEasy:-An-open-source-chin-rest-for-human-psychophysics-experiments) wiki page to give more comprehensive information on how to manufacture and assemble this chin rest design. The FreeCAD and .stl files will be available on [Thingiverse](https://www.thingiverse.com/thing:2968729) in the next few days. I will update you when they become available for download.

**Comment by arnabiswas** [comment]
Thank you very much.  Thanks also for keeping things open source :)

**Comment by matdryhurst** [comment]
These STL files seem to have disappeared from Thingiverse! Any chance you would mind uploading them please?

**Comment by Tractarian** [comment]
Me too - I'd be very keen to find these files. There doesn't seem to be anything else available anywhere else.

**Comment by pikelets** [comment]
Also very keen for the files, would love to make one or two of these devices to save some cash in the lab!

**Comment by Phenomenal-Cat** [comment]
I'm terribly sorry folks, it seems I had neglected to hit the 'publish thing' button! The .stl files are now online here: https://www.thingiverse.com/thing:2968729. However, this initial design is far from optimal (too much solid plastic) and would currently not be cost efficient unless you have access to your own 3D printer. I've uploaded the [FreeCAD](https://www.freecadweb.org/) file (.FCStd) on the Thingiverse page in case anybody wants to have a crack at making some improvements.

**Comment by pikelets** [comment]
Thanks very much MonkeyGone2Heaven!

**Comment by pikelets** [comment]
Thanks again for uploading the files on Thingiverse. I was wondering if you might also have the .stl and .FCStd files for the metric version? Seems like the spaces for the profiles in the chin bar, clamp etc are sized for a profile of roughly 1" x 1"

**Comment by chris-zielinski** [comment]
Thank you for sharing this solution! We plan to use it for an eye-tracking experiment. Would it be possible to update the link to the FreeCAD file (.FCStd)? Thank you in advance.

**Comment by KatGial** [comment]
> Files may be missing. I could not find the link to the CAD files or .STL file for custom parts of the Rest Easy open source chinrest.

The files are still missing, and the page can't even load

**Comment by KatGial** [comment]
Files may be missing. I could not find the link to the CAD files or .STL file for custom parts of the Rest Easy open source chinrest.

**Comment by Phenomenal-Cat** [comment]
Hi all, it appears that the Thingiverse.com website is currently down (https://www.isitdownrightnow.com/thingiverse.com.html). I will try to find somewhere else to host the .stl and CAD files and documentation. In the meantime, the files can be downloaded here: https://drive.google.com/drive/folders/1sYwiJuLq_BLGtpy56RgK8D5UHR0CFBos?usp=sharing

**Comment by chris-zielinski** [comment]
Youhou! Thank you very much for the quick answer!

**Comment by KatGial** [comment]
Thank you so much for this!
________________________________
Από: Aidan Murphy <notifications@github.com>
Στάλθηκε: Πέμπτη, 1 Αυγούστου 2019 4:13 μμ
Προς: nimh-nif/SCNI_Toolbar <SCNI_Toolbar@noreply.github.com>
Κοιν.: KatGial <kat__erina@windowslive.com>; Comment <comment@noreply.github.com>
Θέμα: Re: [nimh-nif/SCNI_Toolbar] Rest easy (open source chin rest) files (#4)


Hi all, it appears that the Thingiverse.com website is currently down (https://www.isitdownrightnow.com/thingiverse.com.html). I will try to find somewhere else to host the .stl and CAD files and documentation. In the meantime, the files can be downloaded here: https://drive.google.com/drive/folders/1sYwiJuLq_BLGtpy56RgK8D5UHR0CFBos?usp=sharing
