### ISSUE TITLE
HSSTB5-2020-600-TPW no longer available...

### ISSUE THREAD

**Issue by PsyTechMMU** [MonkeyGone2Heaven/SCNI_Toolbar#6]
Thanks for the design, resources, and all the work that must have gone into this project. I'm looking to build my first soon (possibly of several) for the department of Psychology at Manchester Metropolitan University. Part HSSTB5-2020-600-TPW doesn't seem to be available from Misumi any more, though, so I'd like to know if part HFSB5-2020-600-TPW would be a close enough fit to be an alternative.

(Apologies, this kind of work and building etc. is not my forte!)

**Comment by Phenomenal-Cat** [comment]
Yeah, I'm afraid I haven't updated the details or the 3D-printed parts for the metric (UK/EU) version in a while. I'm just checking the Misumi website now and will update the part numbers on this list, but it may require some edits to the 3D-printed part designs also. I'll let you know when I have everything updated and hopefully we can get you a successful first build!

**Comment by PsyTechMMU** [comment]
Thank you for the response and thank you so much (in advance) for updating the info. I look forward to being able to try building one.

Gary

**Comment by Phenomenal-Cat** [comment]
Hi Gary. I've updated the list of [Misumi parts](https://github.com/nimh-nif/SCNI_Toolbar/wiki/RestEasy:-An-open-source-chin-rest-for-human-psychophysics-experiments#commercially-available-parts) for the metric version of the RestEasy on the Wiki, and also made some edits to the 3D-print parts for this version, which can now be downloaded from [Thingiverse](https://www.thingiverse.com/thing:2968729). 

I'm not aware of anyone making the metric version yet, so it's possible I've [messed up](https://github.com/nimh-nif/SCNI_Toolbar/issues/5) somewhere! However, I have uploaded the original FreeCAD file for both versions to Thingiverse, so you are welcome to make your own edits or switch out alternative hardware if you like.

Unless you have access to a suitable 3D-printer, the main challenge is finding reasonably priced prototyping services to 3D-print the plastic parts in a strong enough material. If you can let me know how you get on with that it could be useful information for others in the UK considering making one of these. There's also the possibility of switching the table clamps for off-the-shelf metal clamps, which would reduce the cost of the 3D-printing parts. I just need to find a suitable model of clamp that is widely available and design a part to connect it to the aluminium t-slot profile.

Hope this helps!
Aidan

**Comment by PsyTechMMU** [comment]
You and that are amazing! Thank you so much for doing that and so quickly too. I will be looking into it in more detail next week and will certainly update you with how I get on. Thankfully, we have quite large print department and an array of 3D-printing resources here at MMU, so hopefully the prototyping should be straight forward enough. Thanks again.

"Before acting on this email or opening any attachments you should read the Manchester Metropolitan University email disclaimer available on its website http://www.mmu.ac.uk/emaildisclaimer "
